### ISSUE TITLE
listFinancialEvents() doesn't work It does not work and returns error

### ISSUE THREAD

**Issue by valle50** [clousale/amazon-sp-api-php#141]
I want to obtain all the information of the transactions of each order, I found the class "FinancesApi ()", which seems to do what I am looking for, but when doing the test with the example that comes with the demo, it does not work and I returned the following error:

`Fatal error: Uncaught Error: Class '\ClouSale\AmazonSellingPartnerAPI\Models\Finances\DateTime' not found in C:\xampp\htdocs\prueba_aws\vendor\clousale\amazon-sp-api-php\lib\ObjectSerializer.php:294 Stack trace: #0 C:\xampp\htdocs\prueba_aws\vendor\clousale\amazon-sp-api-php\lib\ObjectSerializer.php(311): ClouSale\AmazonSellingPartnerAPI\ObjectSerializer::deserialize('2021-10-07T18:0...', '\\ClouSale\\Amazo...', NULL) #1 C:\xampp\htdocs\prueba_aws\vendor\clousale\amazon-sp-api-php\lib\ObjectSerializer.php(243): ClouSale\AmazonSellingPartnerAPI\ObjectSerializer::deserialize(Object(stdClass), 'ClouSale\\Amazon...', NULL) #2 C:\xampp\htdocs\prueba_aws\vendor\clousale\amazon-sp-api-php\lib\ObjectSerializer.php(311): ClouSale\AmazonSellingPartnerAPI\ObjectSerializer::deserialize(Array, '\\ClouSale\\Amazo...', NULL) #3 C:\xampp\htdocs\prueba_aws\vendor\clousale\amazon-sp-api-php\lib\ObjectSerializer.php(311): ClouSale\AmazonSellingPartnerAPI\ObjectSerializer::deserialize(Object(stdClass), '\\ClouSale\\Amazo...', NULL) #4`

I call the function like this:

`$apiInstance = new \ClouSale\AmazonSellingPartnerAPI\Api\FinancesApi($config);
 $after = "2021-10-07T10:00:00-05:00";
 $before = "2021-10-17T19:00:00-05:00";

 $result = $apiInstance->listFinancialEvents(50, $after, $before);`

**Comment by geekworm-com** [comment]
@valle50 Hi, please refer to the above
