### ISSUE TITLE
POST https://sts.amazonaws.com/` resulted in a `403 Forbidden` response

### ISSUE THREAD

**Issue by miumiu5228** [clousale/amazon-sp-api-php#159]
When I run the script (IRM role), I have the following error in the command. 

```
Fatal error: require_once(): Failed opening required './vendor/autoload.php' (include_path='.:') in /Users/lingchen/Desktop/test.php on line 3
(base) lingchen@Lings-MacBook-Air desktop % php test.php
Error (Signing process) : Client error: `POST https://sts.amazonaws.com/` resulted in a `403 Forbidden` response:
{"Error":{"Code":"AccessDenied","Message":"User: arn:aws:iam::237249205872:user/lingchen is not authorized to perform: s (truncated...)

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://sts.amazonaws.com/` resulted in a `403 Forbidden` response:
{"Error":{"Code":"AccessDenied","Message":"User: arn:aws:iam::237249205872:user/lingchen is not authorized to perform: s (truncated...)
 in /Users/lingchen/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /Users/lingchen/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /Users/lingchen/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Users/lingchen/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /Users/lingchen/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /Users/lingchen/vendor/guzzl in /Users/lingchen/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

May I ask help about this?

**Comment by Johnny99211** [comment]
https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities
